default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: pley_development

test:
  <<: *default
  database: pley_test

production:
  <<: *default
database: pley_production
