# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 525ad78d88a1d6778952c0224cf081d0915eea16d130311e671c1e4ff7dbd9f79eda3a0c5c9d5afa0de028f6d7f0e34670fda4bbf4de903ea098a69e580aaf02
  facebook_app_id: <=% ENV["FB_APP_ID"] %> #changed to tams
  facebook_app_secret: <=% ENV["FB_PLEY_APP_SECRET"] %>

test:
  secret_key_base: 853f89bcf4773369d6449ea76aeb701f5cd8196837395454d3e53b235c5e58ed0a96b6c92f498f3304ec05d937ba8f0803c5757585c0ae19f1cf101bdd6ab1f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <=% ENV["FB_APP_ID"] %>
  facebook_app_secret: <=% ENV["FB_PLEY_APP_SECRET"] %>
